/* This file is autogenerated, do not edit*/
#include "Main.out_automoc.dir/moc_mainwindow_HTAHOQYZHKV5SN.cpp"
#include "Main.out_automoc.dir/moc_objectlist_LBMD7DPNHMRVKU.cpp"
#include "Main.out_automoc.dir/moc_zonelist_2J2RHGYHPWX67J.cpp"
